openapi: 3.1.0
info:
  title: OpenSearch Index Rollups API
  description: OpenSearch Index Rollups API
  version: 1.0.0
paths:
  /_plugins/_rollup/jobs/{id}:
    get:
      operationId: rollups.get_rollup.0
      x-operation-group: rollups.get_rollup
      x-version-added: 1.0
      description: Get an index rollup.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-rollups/rollup-api/#get-an-index-rollup-job
      parameters:
        - $ref: '#/components/parameters/rollups.get_rollup::path.id'
      responses:
        '200':
          $ref: '#/components/responses/rollups.get_rollup@200'
    put:
      operationId: rollups.put_rollup.0
      x-operation-group: rollups.put_rollup
      x-version-added: 1.0
      description: Create or update index rollup.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-rollups/rollup-api/#create-or-update-an-index-rollup-job
      responses:
        '200':
          $ref: '#/components/responses/rollups.put_rollup@200'
      parameters:
        - $ref: '#/components/parameters/rollups.put_rollup::path.id'
        - $ref: '#/components/parameters/rollups.put_rollup::query.if_seq_no'
        - $ref: '#/components/parameters/rollups.put_rollup::query.if_primary_term'
      requestBody:
        $ref: '#/components/requestBodies/rollups.put_rollup'
    delete:
      operationId: rollups.delete_rollup.0
      x-operation-group: rollups.delete_rollup
      x-version-added: 1.0
      description: Delete index rollup.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-rollups/rollup-api/#delete-an-index-rollup-job
      responses:
        '200':
          $ref: '#/components/responses/rollups.delete_rollup@200'
      parameters:
        - $ref: '#/components/parameters/rollups.delete_rollup::path.id'
  /_plugins/_rollup/jobs/{id}/_start:
    post:
      operationId: rollups.start_rollup.0
      x-operation-group: rollups.start_rollup
      x-version-added: 1.0
      description: Start rollup.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-rollups/rollup-api/#start-or-stop-an-index-rollup-job
      parameters:
        - $ref: '#/components/parameters/rollups.start_rollup::path.id'
      responses:
        '200':
          $ref: '#/components/responses/rollups.start_rollup@200'
  /_plugins/_rollup/jobs/{id}/_stop:
    post:
      operationId: rollups.stop_rollup.0
      x-operation-group: rollups.stop_rollup
      x-version-added: 1.0
      description: Stop rollup.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-rollups/rollup-api/#start-or-stop-an-index-rollup-job
      parameters:
        - $ref: '#/components/parameters/rollups.stop_rollup::path.id'
      responses:
        '200':
          $ref: '#/components/responses/rollups.stop_rollup@200'
  /_plugins/_rollup/jobs/{id}/_explain:
    get:
      operationId: rollups.explain.0
      x-operation-group: rollups.explain
      x-version-added: 1.0
      description: Get a rollup's current status.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-rollups/rollup-api/#explain-an-index-rollup-job
      parameters:
        - $ref: '#/components/parameters/rollups.explain::path.id'
      responses:
        '200':
          $ref: '#/components/responses/rollups.explain@200'
components:
  requestBodies:
    rollups.put_rollup:
      content:
        application/json:
          schema:
            $ref: '../schemas/rollups._common.yaml#/components/schemas/RollupEntity'
  responses:
    rollups.get_rollup@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/rollups._common.yaml#/components/schemas/RollupEntity'
    rollups.put_rollup@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/rollups._common.yaml#/components/schemas/RollupEntity'
    rollups.delete_rollup@200:
      description: ''
    rollups.start_rollup@200:
      description: ''
    rollups.stop_rollup@200:
      description: ''
    rollups.explain@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/rollups._common.yaml#/components/schemas/ExplainEntities'
  parameters:
    rollups.get_rollup::path.id:
      name: id
      in: path
      description: Rollup to access
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    rollups.put_rollup::path.id:
      name: id
      in: path
      description: Rollup to access
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    rollups.delete_rollup::path.id:
      name: id
      in: path
      description: Rollup to access
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    rollups.start_rollup::path.id:
      name: id
      in: path
      description: Rollup to access
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    rollups.stop_rollup::path.id:
      name: id
      in: path
      description: Rollup to access
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    rollups.explain::path.id:
      name: id
      in: path
      description: Rollup to access
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    rollups.put_rollup::query.if_seq_no:
      name: if_seq_no
      in: query
      description: Only perform the operation if the document has this sequence number.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/SequenceNumber'
      style: form
    rollups.put_rollup::query.if_primary_term:
      name: if_primary_term
      in: query
      description: Only perform the operation if the document has this primary term.
      schema:
        type: number
      style: form
